'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.8745
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o vuelva a generar su proyecto de VS.
    '''<summary>
    '''  Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CONTABILIDAD.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _16__Acrobat_() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_16__Acrobat_", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property _16__Address_book_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16 (Address book)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _16__Align_left_4_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16 (Align left-4)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _16__Align_left_4_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16 (Align left-4)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _16__Align_right_4_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16 (Align right-4)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _16__Arrow_last_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16 (Arrow last)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _16__Arrow_last_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16 (Arrow last)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _16__Binoculars_2_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16 (Binoculars-2)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _16__Cabinet_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16 (Cabinet)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _16__Cancel_() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_16__Cancel_", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property _16__Cancel_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16 (Cancel)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _16__Card_file_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16 (Card file)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _16__Card_file_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16 (Card file)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _16__Computer_() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_16__Computer_", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property _16__Db_last_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16 (Db last)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _16__Db_next_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16 (Db next)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _16__Delete_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16 (Delete)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _16__Edit_2_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16 (Edit-2)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _16__Exit_() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_16__Exit_", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property _16__File_new_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16 (File new)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _16__Find_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16 (Find)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _16__Folder_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16 (Folder)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _16__Folder_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16 (Folder)2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _16__Folder_search_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16 (Folder search)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _16__Next_set_2_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16 (Next-set 2)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _16__Ok_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16 (Ok)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _16__Ok_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16 (Ok)11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _16__Print_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16 (Print)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _16__Refresh_() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_16__Refresh_", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property _16__Refresh_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16 (Refresh)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _16__Refresh_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16 (Refresh)11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _16__Save_() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_16__Save_", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property _16__Save_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16 (Save)11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _16__Save_2() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_16__Save_2", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property _16__Save_as_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16 (Save as)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _16__Screen_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16 (Screen)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _16__Screen_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16 (Screen)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _16__Search_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16 (Search)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _16__Stop_2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16 (Stop-2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _16__Stop_2_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16 (Stop-2)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _16__View_page_width_3_() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_16__View_page_width_3_", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property _32621071() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("32621071", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _7_453_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("7(453)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Administracion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Administracion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Administracion1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Administracion1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Administracion11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Administracion11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Administracion2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Administracion2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blanco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blanco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property carrito_1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("carrito_1_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property collapse() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("collapse", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property compras() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("compras", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Copia__2__de_84_1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Copia__2__de_84_1_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Copia_de_84_1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Copia_de_84_1_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property copiar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("copiar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property excel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("excel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property expand() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("expand", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fondo3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fondo3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fondo31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fondo31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gestion_documental_cuentas_por_pagar_01_1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gestion_documental_cuentas_por_pagar_01_1_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images_9_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images_9_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo_sunat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_sunat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property notepad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("notepad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ORDEN_20Y_20CONTROL_20DE_20INVENTARIOS_1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ORDEN_20Y_20CONTROL_20DE_20INVENTARIOS_1_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pegar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pegar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sist_inventarios_1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sist_inventarios_1_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sunat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sunat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tipeo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tipeo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
