'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.8009
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=2.0.50727.8009.
'
Namespace FacturacionNWS
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="BasicHttpBinding_IFacturacionNService", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class FacturacionNService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private EnviarGuiaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private EnviarRetencionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.CONTABILIDAD.My.MySettings.Default.CONTABILIDAD_FacturacionNWS_FacturacionNService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event EnviarGuiaCompleted As EnviarGuiaCompletedEventHandler
        
        '''<remarks/>
        Public Event EnviarRetencionCompleted As EnviarRetencionCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IFacturacionNService/EnviarGuia", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EnviarGuia(<System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal archivo() As Byte) As transactionResponse()
            Dim results() As Object = Me.Invoke("EnviarGuia", New Object() {archivo})
            Return CType(results(0),transactionResponse())
        End Function
        
        '''<remarks/>
        Public Overloads Sub EnviarGuiaAsync(ByVal archivo() As Byte)
            Me.EnviarGuiaAsync(archivo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EnviarGuiaAsync(ByVal archivo() As Byte, ByVal userState As Object)
            If (Me.EnviarGuiaOperationCompleted Is Nothing) Then
                Me.EnviarGuiaOperationCompleted = AddressOf Me.OnEnviarGuiaOperationCompleted
            End If
            Me.InvokeAsync("EnviarGuia", New Object() {archivo}, Me.EnviarGuiaOperationCompleted, userState)
        End Sub
        
        Private Sub OnEnviarGuiaOperationCompleted(ByVal arg As Object)
            If (Not (Me.EnviarGuiaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EnviarGuiaCompleted(Me, New EnviarGuiaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IFacturacionNService/EnviarRetencion", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EnviarRetencion(<System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal archivo() As Byte) As transactionResponse()
            Dim results() As Object = Me.Invoke("EnviarRetencion", New Object() {archivo})
            Return CType(results(0),transactionResponse())
        End Function
        
        '''<remarks/>
        Public Overloads Sub EnviarRetencionAsync(ByVal archivo() As Byte)
            Me.EnviarRetencionAsync(archivo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EnviarRetencionAsync(ByVal archivo() As Byte, ByVal userState As Object)
            If (Me.EnviarRetencionOperationCompleted Is Nothing) Then
                Me.EnviarRetencionOperationCompleted = AddressOf Me.OnEnviarRetencionOperationCompleted
            End If
            Me.InvokeAsync("EnviarRetencion", New Object() {archivo}, Me.EnviarRetencionOperationCompleted, userState)
        End Sub
        
        Private Sub OnEnviarRetencionOperationCompleted(ByVal arg As Object)
            If (Not (Me.EnviarRetencionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EnviarRetencionCompleted(Me, New EnviarRetencionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.8018"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://service.connector.alfa1lab.efact/")>  _
    Partial Public Class transactionResponse
        
        Private cdrFileField() As Byte
        
        Private digestValueField As String
        
        Private identifierField As String
        
        Private outStringField As String
        
        Private pdfFileField() As Byte
        
        Private responseCodeField As Integer
        
        Private sunatErrorField As sunatError
        
        Private uuidField As String
        
        Private xmlSignedField() As Byte
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")>  _
        Public Property cdrFile() As Byte()
            Get
                Return Me.cdrFileField
            End Get
            Set
                Me.cdrFileField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property digestValue() As String
            Get
                Return Me.digestValueField
            End Get
            Set
                Me.digestValueField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property identifier() As String
            Get
                Return Me.identifierField
            End Get
            Set
                Me.identifierField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property outString() As String
            Get
                Return Me.outStringField
            End Get
            Set
                Me.outStringField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")>  _
        Public Property pdfFile() As Byte()
            Get
                Return Me.pdfFileField
            End Get
            Set
                Me.pdfFileField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property responseCode() As Integer
            Get
                Return Me.responseCodeField
            End Get
            Set
                Me.responseCodeField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property sunatError() As sunatError
            Get
                Return Me.sunatErrorField
            End Get
            Set
                Me.sunatErrorField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property uuid() As String
            Get
                Return Me.uuidField
            End Get
            Set
                Me.uuidField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")>  _
        Public Property xmlSigned() As Byte()
            Get
                Return Me.xmlSignedField
            End Get
            Set
                Me.xmlSignedField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.8018"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://service.connector.alfa1lab.efact/")>  _
    Partial Public Class sunatError
        
        Private messageField As String
        
        Private sunatErrorCodeField As Integer
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property sunatErrorCode() As Integer
            Get
                Return Me.sunatErrorCodeField
            End Get
            Set
                Me.sunatErrorCodeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")>  _
    Public Delegate Sub EnviarGuiaCompletedEventHandler(ByVal sender As Object, ByVal e As EnviarGuiaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EnviarGuiaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As transactionResponse()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),transactionResponse())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")>  _
    Public Delegate Sub EnviarRetencionCompletedEventHandler(ByVal sender As Object, ByVal e As EnviarRetencionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EnviarRetencionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As transactionResponse()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),transactionResponse())
            End Get
        End Property
    End Class
End Namespace
